/* eslint-disable */
import { requestFromContract } from "./contractApi";

const buildRequester = (service, controller, method, pathTemplate, description) => {
  return (payload = {}) => requestFromContract({ service, controller, method, pathTemplate, descriptionIncludes: description }, payload);
};

export const generatedApiClient = {
  "api_gateway": {
    "session_management": {
      "getGetUserSessions": buildRequester("api_gateway", "session_management", "GET", "/sessions", "Get user sessions"),
      "deleteDeactivateSpecificSession": buildRequester("api_gateway", "session_management", "DELETE", "/sessions/{sessionId}", "Deactivate specific session"),
      "postDeactivateOtherSessions": buildRequester("api_gateway", "session_management", "POST", "/sessions/deactivate-others", "Deactivate other sessions"),
      "postDeactivateAllSessions": buildRequester("api_gateway", "session_management", "POST", "/sessions/deactivate-all", "Deactivate all sessions"),
      $meta: [
        { method: "GET", pathTemplate: "/sessions", description: "Get user sessions", authRequired: true, authType: "X-User-Id, X-Session-Id headers" },
        { method: "DELETE", pathTemplate: "/sessions/{sessionId}", description: "Deactivate specific session", authRequired: true, authType: "X-User-Id, X-Session-Id headers" },
        { method: "POST", pathTemplate: "/sessions/deactivate-others", description: "Deactivate other sessions", authRequired: true, authType: "X-User-Id, X-Session-Id headers" },
        { method: "POST", pathTemplate: "/sessions/deactivate-all", description: "Deactivate all sessions", authRequired: true, authType: "X-User-Id header" },
      ],
    },
  },
  "user_service": {
    "user_controller": {
      "getGetCurrentUserProfile": buildRequester("user_service", "user_controller", "GET", "/users/me", "Get current user profile"),
      "putUpdateCurrentUserProfile": buildRequester("user_service", "user_controller", "PUT", "/users/me", "Update current user profile"),
      "postUploadProfilePhoto": buildRequester("user_service", "user_controller", "POST", "/users/me/photo", "Upload profile photo"),
      "deleteDeleteUserAccount": buildRequester("user_service", "user_controller", "DELETE", "/users/me", "Delete user account"),
      "getGetAllUsersAdmin": buildRequester("user_service", "user_controller", "GET", "/users", "Get all users (Admin)"),
      "getGetUserById": buildRequester("user_service", "user_controller", "GET", "/users/{id}", "Get user by ID"),
      "putUpdateUserStatus": buildRequester("user_service", "user_controller", "PUT", "/users/{id}/status", "Update user status"),
      "deleteDeleteUserById": buildRequester("user_service", "user_controller", "DELETE", "/users/{id}", "Delete user by ID"),
      $meta: [
        { method: "GET", pathTemplate: "/users/me", description: "Get current user profile", authRequired: true, authType: "Bearer Token" },
        { method: "PUT", pathTemplate: "/users/me", description: "Update current user profile", authRequired: true, authType: "Bearer Token" },
        { method: "POST", pathTemplate: "/users/me/photo", description: "Upload profile photo", authRequired: true, authType: "Bearer Token" },
        { method: "DELETE", pathTemplate: "/users/me", description: "Delete user account", authRequired: true, authType: "Bearer Token" },
        { method: "GET", pathTemplate: "/users", description: "Get all users (Admin)", authRequired: true, authType: "Service Token or Admin" },
        { method: "GET", pathTemplate: "/users/{id}", description: "Get user by ID", authRequired: true, authType: "Admin" },
        { method: "PUT", pathTemplate: "/users/{id}/status", description: "Update user status", authRequired: true, authType: "Admin" },
        { method: "DELETE", pathTemplate: "/users/{id}", description: "Delete user by ID", authRequired: true, authType: "Admin" },
      ],
    },
    "registration_controller": {
      "postRegisterNewUserSendsOtp": buildRequester("user_service", "registration_controller", "POST", "/auth/register", "Register new user (sends OTP)"),
      "postVerifyEmailWithOtp": buildRequester("user_service", "registration_controller", "POST", "/auth/verify-email", "Verify email with OTP"),
      $meta: [
        { method: "POST", pathTemplate: "/auth/register", description: "Register new user (sends OTP)", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/auth/verify-email", description: "Verify email with OTP", authRequired: false, authType: "None" },
      ],
    },
    "unified_authentication_controller": {
      "postUnifiedLoginStudentInstructorAdmin": buildRequester("user_service", "unified_authentication_controller", "POST", "/auth/login", "Unified login (Student/Instructor/Admin)"),
      "postRefreshAccessToken": buildRequester("user_service", "unified_authentication_controller", "POST", "/auth/refresh", "Refresh access token"),
      "postLogoutUser": buildRequester("user_service", "unified_authentication_controller", "POST", "/auth/logout", "Logout user"),
      "postRequestLoginOtp": buildRequester("user_service", "unified_authentication_controller", "POST", "/auth/login/otp/request", "Request login OTP"),
      "postVerifyLoginOtp": buildRequester("user_service", "unified_authentication_controller", "POST", "/auth/login/otp/verify", "Verify login OTP"),
      "postForgotPasswordSendsOtp": buildRequester("user_service", "unified_authentication_controller", "POST", "/auth/password/forgot", "Forgot password (sends OTP)"),
      "postVerifyPasswordResetOtp": buildRequester("user_service", "unified_authentication_controller", "POST", "/auth/password/verify-otp", "Verify password reset OTP"),
      "postResetPassword": buildRequester("user_service", "unified_authentication_controller", "POST", "/auth/password/reset", "Reset password"),
      "postChangePasswordAuthenticated": buildRequester("user_service", "unified_authentication_controller", "POST", "/auth/change-password", "Change password (authenticated)"),
      "postSwitchUserRole": buildRequester("user_service", "unified_authentication_controller", "POST", "/auth/switch-role", "Switch user role"),
      $meta: [
        { method: "POST", pathTemplate: "/auth/login", description: "Unified login (Student/Instructor/Admin)", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/auth/refresh", description: "Refresh access token", authRequired: true, authType: "Bearer Token (Refresh)" },
        { method: "POST", pathTemplate: "/auth/logout", description: "Logout user", authRequired: true, authType: "Bearer Token" },
        { method: "POST", pathTemplate: "/auth/login/otp/request", description: "Request login OTP", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/auth/login/otp/verify", description: "Verify login OTP", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/auth/password/forgot", description: "Forgot password (sends OTP)", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/auth/password/verify-otp", description: "Verify password reset OTP", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/auth/password/reset", description: "Reset password", authRequired: false, authType: "Optional Bearer Token" },
        { method: "POST", pathTemplate: "/auth/change-password", description: "Change password (authenticated)", authRequired: true, authType: "Bearer Token" },
        { method: "POST", pathTemplate: "/auth/switch-role", description: "Switch user role", authRequired: true, authType: "Bearer Token" },
      ],
    },
    "session_controller": {
      "getListAllUserSessions": buildRequester("user_service", "session_controller", "GET", "/users/me/sessions", "List all user sessions"),
      "deleteLogoutSpecificDevice": buildRequester("user_service", "session_controller", "DELETE", "/users/me/sessions/{id}", "Logout specific device"),
      "deleteLogoutFromAllSessions": buildRequester("user_service", "session_controller", "DELETE", "/users/me/sessions", "Logout from all sessions"),
      $meta: [
        { method: "GET", pathTemplate: "/users/me/sessions", description: "List all user sessions", authRequired: true, authType: "Bearer Token" },
        { method: "DELETE", pathTemplate: "/users/me/sessions/{id}", description: "Logout specific device", authRequired: true, authType: "Bearer Token" },
        { method: "DELETE", pathTemplate: "/users/me/sessions", description: "Logout from all sessions", authRequired: true, authType: "Bearer Token" },
      ],
    },
    "instructor_controller": {
      "postApplyForInstructorMultipart": buildRequester("user_service", "instructor_controller", "POST", "/instructors/applications", "Apply for instructor (multipart)"),
      "getGetApplicationStatus": buildRequester("user_service", "instructor_controller", "GET", "/instructors/applications/me", "Get application status"),
      $meta: [
        { method: "POST", pathTemplate: "/instructors/applications", description: "Apply for instructor (multipart)", authRequired: true, authType: "Bearer Token" },
        { method: "GET", pathTemplate: "/instructors/applications/me", description: "Get application status", authRequired: true, authType: "Bearer Token" },
      ],
    },
    "admin_instructor_controller": {
      "getGetAllApprovedInstructors": buildRequester("user_service", "admin_instructor_controller", "GET", "/admin/instructors", "Get all approved instructors"),
      "getGetAllInstructorApplications": buildRequester("user_service", "admin_instructor_controller", "GET", "/admin/instructors/applications", "Get all instructor applications"),
      "putApproveInstructorApplication": buildRequester("user_service", "admin_instructor_controller", "PUT", "/admin/instructors/applications/{userId}/approve", "Approve instructor application"),
      "putRejectInstructorApplication": buildRequester("user_service", "admin_instructor_controller", "PUT", "/admin/instructors/applications/{userId}/reject", "Reject instructor application"),
      $meta: [
        { method: "GET", pathTemplate: "/admin/instructors", description: "Get all approved instructors", authRequired: true, authType: "@PreAuthorize: MAIN_ADMIN, SUB_ADMIN" },
        { method: "GET", pathTemplate: "/admin/instructors/applications", description: "Get all instructor applications", authRequired: true, authType: "@PreAuthorize: MAIN_ADMIN, SUB_ADMIN" },
        { method: "PUT", pathTemplate: "/admin/instructors/applications/{userId}/approve", description: "Approve instructor application", authRequired: true, authType: "@PreAuthorize: MAIN_ADMIN, SUB_ADMIN" },
        { method: "PUT", pathTemplate: "/admin/instructors/applications/{userId}/reject", description: "Reject instructor application", authRequired: true, authType: "@PreAuthorize: MAIN_ADMIN, SUB_ADMIN" },
      ],
    },
  },
  "admin_service": {
    "admin_controller": {
      "postRegisterSubAdmin": buildRequester("admin_service", "admin_controller", "POST", "/admin/register", "Register sub-admin"),
      "postAdminPasswordLogin": buildRequester("admin_service", "admin_controller", "POST", "/admin/login", "Admin password login"),
      "postRequestAdminLoginOtp": buildRequester("admin_service", "admin_controller", "POST", "/admin/login/otp/request", "Request admin login OTP"),
      "postVerifyAdminLoginOtp": buildRequester("admin_service", "admin_controller", "POST", "/admin/login/otp/verify", "Verify admin login OTP"),
      "postAdminForgotPassword": buildRequester("admin_service", "admin_controller", "POST", "/admin/password/forgot", "Admin forgot password"),
      "postVerifyAdminPasswordOtp": buildRequester("admin_service", "admin_controller", "POST", "/admin/password/verify-otp", "Verify admin password OTP"),
      "postResetAdminPassword": buildRequester("admin_service", "admin_controller", "POST", "/admin/password/reset", "Reset admin password"),
      "putUpdateAdminProfile": buildRequester("admin_service", "admin_controller", "PUT", "/admin/me", "Update admin profile"),
      "getGetAdminProfile": buildRequester("admin_service", "admin_controller", "GET", "/admin/me", "Get admin profile"),
      $meta: [
        { method: "POST", pathTemplate: "/admin/register", description: "Register sub-admin", authRequired: true, authType: "Main Admin Bearer Token" },
        { method: "POST", pathTemplate: "/admin/login", description: "Admin password login", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/admin/login/otp/request", description: "Request admin login OTP", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/admin/login/otp/verify", description: "Verify admin login OTP", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/admin/password/forgot", description: "Admin forgot password", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/admin/password/verify-otp", description: "Verify admin password OTP", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/admin/password/reset", description: "Reset admin password", authRequired: false, authType: "None" },
        { method: "PUT", pathTemplate: "/admin/me", description: "Update admin profile", authRequired: true, authType: "@AuthenticationPrincipal" },
        { method: "GET", pathTemplate: "/admin/me", description: "Get admin profile", authRequired: true, authType: "@AuthenticationPrincipal" },
      ],
    },
    "admin_course_controller": {
      "getGetAllCourses": buildRequester("admin_service", "admin_course_controller", "GET", "/admin/courses", "Get all courses"),
      "getGetCourseById": buildRequester("admin_service", "admin_course_controller", "GET", "/admin/courses/{courseId}", "Get course by ID"),
      "getGetCourseContent": buildRequester("admin_service", "admin_course_controller", "GET", "/admin/content/{courseId}", "Get course content"),
      "putApproveCourse": buildRequester("admin_service", "admin_course_controller", "PUT", "/admin/courses/{courseId}/approve", "Approve course"),
      "putRejectCourse": buildRequester("admin_service", "admin_course_controller", "PUT", "/admin/courses/{courseId}/reject", "Reject course"),
      "deleteDeleteCourse": buildRequester("admin_service", "admin_course_controller", "DELETE", "/admin/courses/{courseId}", "Delete course"),
      "postCreateSection": buildRequester("admin_service", "admin_course_controller", "POST", "/admin/courses/{courseId}/sections", "Create section"),
      "deleteDeleteSection": buildRequester("admin_service", "admin_course_controller", "DELETE", "/admin/sections/{sectionId}", "Delete section"),
      "postCreateLecture": buildRequester("admin_service", "admin_course_controller", "POST", "/admin/sections/{sectionId}/lectures", "Create lecture"),
      "putApproveLecture": buildRequester("admin_service", "admin_course_controller", "PUT", "/admin/sections/{sectionId}/lectures/{lectureId}/approve", "Approve lecture"),
      "putRejectLecture": buildRequester("admin_service", "admin_course_controller", "PUT", "/admin/sections/{sectionId}/lectures/{lectureId}/reject", "Reject lecture"),
      "deleteDeleteLecture": buildRequester("admin_service", "admin_course_controller", "DELETE", "/admin/sections/{sectionId}/lectures/{lectureId}", "Delete lecture"),
      $meta: [
        { method: "GET", pathTemplate: "/admin/courses", description: "Get all courses", authRequired: true, authType: "Admin" },
        { method: "GET", pathTemplate: "/admin/courses/{courseId}", description: "Get course by ID", authRequired: true, authType: "Admin" },
        { method: "GET", pathTemplate: "/admin/content/{courseId}", description: "Get course content", authRequired: true, authType: "Admin" },
        { method: "PUT", pathTemplate: "/admin/courses/{courseId}/approve", description: "Approve course", authRequired: true, authType: "Admin" },
        { method: "PUT", pathTemplate: "/admin/courses/{courseId}/reject", description: "Reject course", authRequired: true, authType: "Admin" },
        { method: "DELETE", pathTemplate: "/admin/courses/{courseId}", description: "Delete course", authRequired: true, authType: "Admin" },
        { method: "POST", pathTemplate: "/admin/courses/{courseId}/sections", description: "Create section", authRequired: true, authType: "Admin" },
        { method: "DELETE", pathTemplate: "/admin/sections/{sectionId}", description: "Delete section", authRequired: true, authType: "Admin" },
        { method: "POST", pathTemplate: "/admin/sections/{sectionId}/lectures", description: "Create lecture", authRequired: true, authType: "Admin" },
        { method: "PUT", pathTemplate: "/admin/sections/{sectionId}/lectures/{lectureId}/approve", description: "Approve lecture", authRequired: true, authType: "Admin" },
        { method: "PUT", pathTemplate: "/admin/sections/{sectionId}/lectures/{lectureId}/reject", description: "Reject lecture", authRequired: true, authType: "Admin" },
        { method: "DELETE", pathTemplate: "/admin/sections/{sectionId}/lectures/{lectureId}", description: "Delete lecture", authRequired: true, authType: "Admin" },
      ],
    },
    "admin_user_controller": {
      "getGetAllUsers": buildRequester("admin_service", "admin_user_controller", "GET", "/admin/users", "Get all users"),
      "getGetUserById": buildRequester("admin_service", "admin_user_controller", "GET", "/admin/users/{id}", "Get user by ID"),
      "putUpdateUserStatus": buildRequester("admin_service", "admin_user_controller", "PUT", "/admin/users/{id}/status", "Update user status"),
      "deleteDeleteUser": buildRequester("admin_service", "admin_user_controller", "DELETE", "/admin/users/{id}", "Delete user"),
      "getGetAllInstructors": buildRequester("admin_service", "admin_user_controller", "GET", "/admin/instructors", "Get all instructors"),
      "getGetInstructorApplications": buildRequester("admin_service", "admin_user_controller", "GET", "/admin/instructors/applications", "Get instructor applications"),
      "putApproveInstructor": buildRequester("admin_service", "admin_user_controller", "PUT", "/admin/instructors/applications/{userId}/approve", "Approve instructor"),
      "deleteDeleteInstructor": buildRequester("admin_service", "admin_user_controller", "DELETE", "/admin/instructors/{id}", "Delete instructor"),
      $meta: [
        { method: "GET", pathTemplate: "/admin/users", description: "Get all users", authRequired: true, authType: "Admin" },
        { method: "GET", pathTemplate: "/admin/users/{id}", description: "Get user by ID", authRequired: true, authType: "Admin" },
        { method: "PUT", pathTemplate: "/admin/users/{id}/status", description: "Update user status", authRequired: true, authType: "Admin" },
        { method: "DELETE", pathTemplate: "/admin/users/{id}", description: "Delete user", authRequired: true, authType: "Admin" },
        { method: "GET", pathTemplate: "/admin/instructors", description: "Get all instructors", authRequired: true, authType: "Admin" },
        { method: "GET", pathTemplate: "/admin/instructors/applications", description: "Get instructor applications", authRequired: true, authType: "Admin" },
        { method: "PUT", pathTemplate: "/admin/instructors/applications/{userId}/approve", description: "Approve instructor", authRequired: true, authType: "Admin" },
        { method: "DELETE", pathTemplate: "/admin/instructors/{id}", description: "Delete instructor", authRequired: true, authType: "Admin" },
      ],
    },
    "admin_order_controller": {
      "getGetAllOrders": buildRequester("admin_service", "admin_order_controller", "GET", "/admin/orders", "Get all orders"),
      "getGetOrderById": buildRequester("admin_service", "admin_order_controller", "GET", "/admin/orders/{id}", "Get order by ID"),
      "putUpdateOrderStatus": buildRequester("admin_service", "admin_order_controller", "PUT", "/admin/orders/{id}/status", "Update order status"),
      "postProcessRefund": buildRequester("admin_service", "admin_order_controller", "POST", "/admin/orders/{id}/refund", "Process refund"),
      $meta: [
        { method: "GET", pathTemplate: "/admin/orders", description: "Get all orders", authRequired: true, authType: "Admin" },
        { method: "GET", pathTemplate: "/admin/orders/{id}", description: "Get order by ID", authRequired: true, authType: "Admin" },
        { method: "PUT", pathTemplate: "/admin/orders/{id}/status", description: "Update order status", authRequired: true, authType: "Admin" },
        { method: "POST", pathTemplate: "/admin/orders/{id}/refund", description: "Process refund", authRequired: true, authType: "Admin" },
      ],
    },
    "admin_payment_controller": {
      "getGetAllPayments": buildRequester("admin_service", "admin_payment_controller", "GET", "/admin/payments", "Get all payments"),
      "getGetPaymentById": buildRequester("admin_service", "admin_payment_controller", "GET", "/admin/payments/{id}", "Get payment by ID"),
      $meta: [
        { method: "GET", pathTemplate: "/admin/payments", description: "Get all payments", authRequired: true, authType: "Admin" },
        { method: "GET", pathTemplate: "/admin/payments/{id}", description: "Get payment by ID", authRequired: true, authType: "Admin" },
      ],
    },
    "admin_report_controller": {
      "getGetUsersReport": buildRequester("admin_service", "admin_report_controller", "GET", "/admin/reports/users", "Get users report"),
      "getGetCoursesReport": buildRequester("admin_service", "admin_report_controller", "GET", "/admin/reports/courses", "Get courses report"),
      "getGetRevenueReport": buildRequester("admin_service", "admin_report_controller", "GET", "/admin/reports/revenue", "Get revenue report"),
      "getGetOrdersReport": buildRequester("admin_service", "admin_report_controller", "GET", "/admin/reports/orders", "Get orders report"),
      "putUpdatePlatformSettings": buildRequester("admin_service", "admin_report_controller", "PUT", "/admin/settings/platform", "Update platform settings"),
      "putUpdatePaymentSettings": buildRequester("admin_service", "admin_report_controller", "PUT", "/admin/settings/payment", "Update payment settings"),
      "putUpdateNotificationSettings": buildRequester("admin_service", "admin_report_controller", "PUT", "/admin/settings/notifications", "Update notification settings"),
      $meta: [
        { method: "GET", pathTemplate: "/admin/reports/users", description: "Get users report", authRequired: true, authType: "@AuthenticationPrincipal" },
        { method: "GET", pathTemplate: "/admin/reports/courses", description: "Get courses report", authRequired: true, authType: "@AuthenticationPrincipal" },
        { method: "GET", pathTemplate: "/admin/reports/revenue", description: "Get revenue report", authRequired: true, authType: "@AuthenticationPrincipal" },
        { method: "GET", pathTemplate: "/admin/reports/orders", description: "Get orders report", authRequired: true, authType: "@AuthenticationPrincipal" },
        { method: "PUT", pathTemplate: "/admin/settings/platform", description: "Update platform settings", authRequired: true, authType: "Admin" },
        { method: "PUT", pathTemplate: "/admin/settings/payment", description: "Update payment settings", authRequired: true, authType: "Admin" },
        { method: "PUT", pathTemplate: "/admin/settings/notifications", description: "Update notification settings", authRequired: true, authType: "Admin" },
      ],
    },
    "admin_review_controller": {
      "getGetAllReviews": buildRequester("admin_service", "admin_review_controller", "GET", "/admin/reviews", "Get all reviews"),
      "deleteDeleteReview": buildRequester("admin_service", "admin_review_controller", "DELETE", "/admin/reviews/{id}", "Delete review"),
      $meta: [
        { method: "GET", pathTemplate: "/admin/reviews", description: "Get all reviews", authRequired: true, authType: "Admin" },
        { method: "DELETE", pathTemplate: "/admin/reviews/{id}", description: "Delete review", authRequired: true, authType: "Admin" },
      ],
    },
  },
  "course_service": {
    "course_controller": {
      "postCreateCourse": buildRequester("course_service", "course_controller", "POST", "/courses", "Create course"),
      "getGetAllCoursesPublic": buildRequester("course_service", "course_controller", "GET", "/courses", "Get all courses (Public)"),
      "getGetCourseByIdPublic": buildRequester("course_service", "course_controller", "GET", "/courses/{id}", "Get course by ID (Public)"),
      "putUpdateCourseFull": buildRequester("course_service", "course_controller", "PUT", "/courses/{id}", "Update course (Full)"),
      "patchUpdateCoursePartial": buildRequester("course_service", "course_controller", "PATCH", "/courses/{id}", "Update course (Partial)"),
      "patchUpdateCourseStatus": buildRequester("course_service", "course_controller", "PATCH", "/courses/{id}/status", "Update course status"),
      "deleteDeleteCourse": buildRequester("course_service", "course_controller", "DELETE", "/courses/{id}", "Delete course"),
      "getGetEnrolledStudents": buildRequester("course_service", "course_controller", "GET", "/courses/{courseId}/students", "Get enrolled students"),
      "postEnrollInFreeCourse": buildRequester("course_service", "course_controller", "POST", "/courses/{courseId}/enroll", "Enroll in free course"),
      $meta: [
        { method: "POST", pathTemplate: "/courses", description: "Create course", authRequired: true, authType: "Instructor/Admin" },
        { method: "GET", pathTemplate: "/courses", description: "Get all courses (Public)", authRequired: false, authType: "None" },
        { method: "GET", pathTemplate: "/courses/{id}", description: "Get course by ID (Public)", authRequired: false, authType: "None" },
        { method: "PUT", pathTemplate: "/courses/{id}", description: "Update course (Full)", authRequired: true, authType: "Instructor/Admin" },
        { method: "PATCH", pathTemplate: "/courses/{id}", description: "Update course (Partial)", authRequired: true, authType: "Instructor/Admin" },
        { method: "PATCH", pathTemplate: "/courses/{id}/status", description: "Update course status", authRequired: true, authType: "Admin Service" },
        { method: "DELETE", pathTemplate: "/courses/{id}", description: "Delete course", authRequired: true, authType: "Instructor/Admin" },
        { method: "GET", pathTemplate: "/courses/{courseId}/students", description: "Get enrolled students", authRequired: false, authType: "Public" },
        { method: "POST", pathTemplate: "/courses/{courseId}/enroll", description: "Enroll in free course", authRequired: true, authType: "Student (JWT)" },
      ],
    },
    "enrollment_controller": {
      "postInternalEnrollmentS2s": buildRequester("course_service", "enrollment_controller", "POST", "/enrollments/internal/enroll", "Internal enrollment (S2S)"),
      "getCheckEnrollmentStatus": buildRequester("course_service", "enrollment_controller", "GET", "/enrollments/check/{courseId}", "Check enrollment status"),
      $meta: [
        { method: "POST", pathTemplate: "/enrollments/internal/enroll", description: "Internal enrollment (S2S)", authRequired: true, authType: "Service-to-Service" },
        { method: "GET", pathTemplate: "/enrollments/check/{courseId}", description: "Check enrollment status", authRequired: true, authType: "JWT Auth" },
      ],
    },
    "course_preview_controller": {
      "postCreateCoursePreview": buildRequester("course_service", "course_preview_controller", "POST", "/courses/{courseId}/preview", "Create course preview"),
      "getGetCoursePreview": buildRequester("course_service", "course_preview_controller", "GET", "/courses/{courseId}/preview", "Get course preview"),
      $meta: [
        { method: "POST", pathTemplate: "/courses/{courseId}/preview", description: "Create course preview", authRequired: true, authType: "Instructor/Admin" },
        { method: "GET", pathTemplate: "/courses/{courseId}/preview", description: "Get course preview", authRequired: false, authType: "Public" },
      ],
    },
    "lecture_controller": {
      "postCreateLecture": buildRequester("course_service", "lecture_controller", "POST", "/sections/{sectionId}/lectures", "Create lecture"),
      "patchUpdateLecture": buildRequester("course_service", "lecture_controller", "PATCH", "/sections/{sectionId}/lectures/{lectureId}", "Update lecture"),
      "deleteDeleteLecture": buildRequester("course_service", "lecture_controller", "DELETE", "/sections/{sectionId}/lectures/{lectureId}", "Delete lecture"),
      "getGetLecturesBySection": buildRequester("course_service", "lecture_controller", "GET", "/sections/{sectionId}/lectures", "Get lectures by section"),
      $meta: [
        { method: "POST", pathTemplate: "/sections/{sectionId}/lectures", description: "Create lecture", authRequired: true, authType: "@PreAuthorize: INSTRUCTOR, ADMIN" },
        { method: "PATCH", pathTemplate: "/sections/{sectionId}/lectures/{lectureId}", description: "Update lecture", authRequired: true, authType: "@PreAuthorize: INSTRUCTOR, ADMIN" },
        { method: "DELETE", pathTemplate: "/sections/{sectionId}/lectures/{lectureId}", description: "Delete lecture", authRequired: true, authType: "@PreAuthorize: INSTRUCTOR, ADMIN" },
        { method: "GET", pathTemplate: "/sections/{sectionId}/lectures", description: "Get lectures by section", authRequired: true, authType: "Enrolled users" },
      ],
    },
    "section_controller": {
      "postCreateSection": buildRequester("course_service", "section_controller", "POST", "/courses/{courseId}/sections", "Create section"),
      "getGetSectionsByCourse": buildRequester("course_service", "section_controller", "GET", "/courses/{courseId}/sections", "Get sections by course"),
      "patchUpdateSection": buildRequester("course_service", "section_controller", "PATCH", "/courses/sections/{sectionId}", "Update section"),
      "deleteDeleteSection": buildRequester("course_service", "section_controller", "DELETE", "/courses/sections/{sectionId}", "Delete section"),
      $meta: [
        { method: "POST", pathTemplate: "/courses/{courseId}/sections", description: "Create section", authRequired: true, authType: "Instructor/Admin" },
        { method: "GET", pathTemplate: "/courses/{courseId}/sections", description: "Get sections by course", authRequired: false, authType: "Public" },
        { method: "PATCH", pathTemplate: "/courses/sections/{sectionId}", description: "Update section", authRequired: true, authType: "Instructor/Admin" },
        { method: "DELETE", pathTemplate: "/courses/sections/{sectionId}", description: "Delete section", authRequired: true, authType: "Instructor/Admin" },
      ],
    },
  },
  "instructor_service": {
    "dashboard_controller": {
      "getGetInstructorDashboard": buildRequester("instructor_service", "dashboard_controller", "GET", "/instructors/{id}/dashboard", "Get instructor dashboard"),
      "getGetInstructorEarnings": buildRequester("instructor_service", "dashboard_controller", "GET", "/instructors/{id}/earnings", "Get instructor earnings"),
      $meta: [
        { method: "GET", pathTemplate: "/instructors/{id}/dashboard", description: "Get instructor dashboard", authRequired: true, authType: "Instructor" },
        { method: "GET", pathTemplate: "/instructors/{id}/earnings", description: "Get instructor earnings", authRequired: true, authType: "Instructor" },
      ],
    },
    "course_controller": {
      "postCreateCourse": buildRequester("instructor_service", "course_controller", "POST", "/instructors/{id}/courses", "Create course"),
      "getGetCoursesByInstructor": buildRequester("instructor_service", "course_controller", "GET", "/instructors/{id}/courses", "Get courses by instructor"),
      "getGetCourseById": buildRequester("instructor_service", "course_controller", "GET", "/instructors/{id}/courses/{courseId}", "Get course by ID"),
      "putUpdateCourse": buildRequester("instructor_service", "course_controller", "PUT", "/instructors/{id}/courses/{courseId}", "Update course"),
      "deleteDeleteUnpublishCourse": buildRequester("instructor_service", "course_controller", "DELETE", "/instructors/{id}/courses/{courseId}", "Delete/unpublish course"),
      "getGetEnrolledStudents": buildRequester("instructor_service", "course_controller", "GET", "/instructors/{id}/courses/{courseId}/students", "Get enrolled students"),
      "getGetStudentProgress": buildRequester("instructor_service", "course_controller", "GET", "/instructors/{id}/courses/{courseId}/students/{studentId}", "Get student progress"),
      "postAssignUpdateGrade": buildRequester("instructor_service", "course_controller", "POST", "/instructors/{id}/courses/{courseId}/grades", "Assign/update grade"),
      "getGetCourseAnalytics": buildRequester("instructor_service", "course_controller", "GET", "/instructors/{id}/courses/{courseId}/analytics", "Get course analytics"),
      $meta: [
        { method: "POST", pathTemplate: "/instructors/{id}/courses", description: "Create course", authRequired: true, authType: "Instructor" },
        { method: "GET", pathTemplate: "/instructors/{id}/courses", description: "Get courses by instructor", authRequired: true, authType: "Instructor" },
        { method: "GET", pathTemplate: "/instructors/{id}/courses/{courseId}", description: "Get course by ID", authRequired: true, authType: "Instructor" },
        { method: "PUT", pathTemplate: "/instructors/{id}/courses/{courseId}", description: "Update course", authRequired: true, authType: "Instructor" },
        { method: "DELETE", pathTemplate: "/instructors/{id}/courses/{courseId}", description: "Delete/unpublish course", authRequired: true, authType: "Instructor" },
        { method: "GET", pathTemplate: "/instructors/{id}/courses/{courseId}/students", description: "Get enrolled students", authRequired: true, authType: "Instructor" },
        { method: "GET", pathTemplate: "/instructors/{id}/courses/{courseId}/students/{studentId}", description: "Get student progress", authRequired: true, authType: "Instructor" },
        { method: "POST", pathTemplate: "/instructors/{id}/courses/{courseId}/grades", description: "Assign/update grade", authRequired: true, authType: "Instructor" },
        { method: "GET", pathTemplate: "/instructors/{id}/courses/{courseId}/analytics", description: "Get course analytics", authRequired: true, authType: "Instructor" },
      ],
    },
    "content_controller": {
      "patchPublishUnpublishContent": buildRequester("instructor_service", "content_controller", "PATCH", "/instructors/{instructorId}/content/{contentId}/publish", "Publish/unpublish content"),
      $meta: [
        { method: "PATCH", pathTemplate: "/instructors/{instructorId}/content/{contentId}/publish", description: "Publish/unpublish content", authRequired: true, authType: "Instructor" },
      ],
    },
    "module_controller": {
      "postAddModule": buildRequester("instructor_service", "module_controller", "POST", "/instructors/{instructorId}/courses/{courseId}/modules", "Add module"),
      "putUpdateModule": buildRequester("instructor_service", "module_controller", "PUT", "/instructors/{instructorId}/courses/{courseId}/modules/{moduleId}", "Update module"),
      "deleteDeleteModule": buildRequester("instructor_service", "module_controller", "DELETE", "/instructors/{instructorId}/courses/{courseId}/modules/{moduleId}", "Delete module"),
      "postUploadResourceMultipart": buildRequester("instructor_service", "module_controller", "POST", "/instructors/{instructorId}/courses/{courseId}/modules/upload", "Upload resource (multipart)"),
      $meta: [
        { method: "POST", pathTemplate: "/instructors/{instructorId}/courses/{courseId}/modules", description: "Add module", authRequired: true, authType: "Instructor" },
        { method: "PUT", pathTemplate: "/instructors/{instructorId}/courses/{courseId}/modules/{moduleId}", description: "Update module", authRequired: true, authType: "Instructor" },
        { method: "DELETE", pathTemplate: "/instructors/{instructorId}/courses/{courseId}/modules/{moduleId}", description: "Delete module", authRequired: true, authType: "Instructor" },
        { method: "POST", pathTemplate: "/instructors/{instructorId}/courses/{courseId}/modules/upload", description: "Upload resource (multipart)", authRequired: true, authType: "Instructor" },
      ],
    },
    "announcement_controller": {
      "postCreateAnnouncement": buildRequester("instructor_service", "announcement_controller", "POST", "/instructors/{id}/courses/{courseId}/announcements", "Create announcement"),
      $meta: [
        { method: "POST", pathTemplate: "/instructors/{id}/courses/{courseId}/announcements", description: "Create announcement", authRequired: true, authType: "Instructor" },
      ],
    },
    "course_message_controller": {
      "postSendCourseMessage": buildRequester("instructor_service", "course_message_controller", "POST", "/instructors/{id}/courses/{courseId}/messages", "Send course message"),
      $meta: [
        { method: "POST", pathTemplate: "/instructors/{id}/courses/{courseId}/messages", description: "Send course message", authRequired: true, authType: "Instructor" },
      ],
    },
    "public_course_controller": {
      "getGetCourseByIdPublic": buildRequester("instructor_service", "public_course_controller", "GET", "/courses/{courseId}", "Get course by ID (Public)"),
      $meta: [
        { method: "GET", pathTemplate: "/courses/{courseId}", description: "Get course by ID (Public)", authRequired: false, authType: "None" },
      ],
    },
  },
  "cart_service": {
    "cart_controller": {
      "postAddCourseToCart": buildRequester("cart_service", "cart_controller", "POST", "/cart", "Add course to cart"),
      "getGetUserCart": buildRequester("cart_service", "cart_controller", "GET", "/cart", "Get user cart"),
      "getGetCartSummary": buildRequester("cart_service", "cart_controller", "GET", "/cart/summary", "Get cart summary"),
      "putApplyCouponToCart": buildRequester("cart_service", "cart_controller", "PUT", "/cart/coupon", "Apply coupon to cart"),
      "deleteRemoveCouponFromCart": buildRequester("cart_service", "cart_controller", "DELETE", "/cart/coupon", "Remove coupon from cart"),
      "deleteRemoveCourseFromCart": buildRequester("cart_service", "cart_controller", "DELETE", "/cart/{courseId}", "Remove course from cart"),
      "deleteClearCart": buildRequester("cart_service", "cart_controller", "DELETE", "/cart", "Clear cart"),
      "postInitiateCheckout": buildRequester("cart_service", "cart_controller", "POST", "/cart/checkout", "Initiate checkout"),
      "getGetCartInternalS2s": buildRequester("cart_service", "cart_controller", "GET", "/cart/internal/{userId}", "Get cart (internal S2S)"),
      "deleteClearCartInternalS2s": buildRequester("cart_service", "cart_controller", "DELETE", "/cart/internal/{userId}", "Clear cart (internal S2S)"),
      $meta: [
        { method: "POST", pathTemplate: "/cart", description: "Add course to cart", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/cart", description: "Get user cart", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/cart/summary", description: "Get cart summary", authRequired: true, authType: "Authentication" },
        { method: "PUT", pathTemplate: "/cart/coupon", description: "Apply coupon to cart", authRequired: true, authType: "Authentication" },
        { method: "DELETE", pathTemplate: "/cart/coupon", description: "Remove coupon from cart", authRequired: true, authType: "Authentication" },
        { method: "DELETE", pathTemplate: "/cart/{courseId}", description: "Remove course from cart", authRequired: true, authType: "Authentication" },
        { method: "DELETE", pathTemplate: "/cart", description: "Clear cart", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/cart/checkout", description: "Initiate checkout", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/cart/internal/{userId}", description: "Get cart (internal S2S)", authRequired: true, authType: "Service-to-Service" },
        { method: "DELETE", pathTemplate: "/cart/internal/{userId}", description: "Clear cart (internal S2S)", authRequired: true, authType: "Service-to-Service" },
      ],
    },
  },
  "coupon_service": {
    "coupon_controller": {
      "postCreateCoupon": buildRequester("coupon_service", "coupon_controller", "POST", "/coupons", "Create coupon"),
      "postBulkGenerateCoupons": buildRequester("coupon_service", "coupon_controller", "POST", "/coupons/bulk", "Bulk generate coupons"),
      "getGetAllCoupons": buildRequester("coupon_service", "coupon_controller", "GET", "/coupons", "Get all coupons"),
      "getGetCouponDetails": buildRequester("coupon_service", "coupon_controller", "GET", "/coupons/{couponId}", "Get coupon details"),
      "getValidateCouponByCode": buildRequester("coupon_service", "coupon_controller", "GET", "/coupons/validate/{code}", "Validate coupon by code"),
      "putUpdateCoupon": buildRequester("coupon_service", "coupon_controller", "PUT", "/coupons/{couponId}", "Update coupon"),
      "deleteDeleteCoupon": buildRequester("coupon_service", "coupon_controller", "DELETE", "/coupons/{couponId}", "Delete coupon"),
      "patchActivateCoupon": buildRequester("coupon_service", "coupon_controller", "PATCH", "/coupons/{couponId}/activate", "Activate coupon"),
      "patchDeactivateCoupon": buildRequester("coupon_service", "coupon_controller", "PATCH", "/coupons/{couponId}/deactivate", "Deactivate coupon"),
      "getGetMyCoupons": buildRequester("coupon_service", "coupon_controller", "GET", "/coupons/my", "Get my coupons"),
      "getGetCampaigns": buildRequester("coupon_service", "coupon_controller", "GET", "/coupons/campaigns", "Get campaigns"),
      "postValidateCouponFull": buildRequester("coupon_service", "coupon_controller", "POST", "/coupons/validate", "Validate coupon (full)"),
      "postGetBestDiscount": buildRequester("coupon_service", "coupon_controller", "POST", "/coupons/best-discount", "Get best discount"),
      "postRedeemCoupon": buildRequester("coupon_service", "coupon_controller", "POST", "/coupons/redeem", "Redeem coupon"),
      "postAssignCouponToUser": buildRequester("coupon_service", "coupon_controller", "POST", "/coupons/assign-user", "Assign coupon to user"),
      $meta: [
        { method: "POST", pathTemplate: "/coupons", description: "Create coupon", authRequired: true, authType: "@PreAuthorize: SERVICE_COUPON_SERVICE, SERVICE_ALL, MAIN_ADMIN, SUB_ADMIN, INSTRUCTOR" },
        { method: "POST", pathTemplate: "/coupons/bulk", description: "Bulk generate coupons", authRequired: true, authType: "@PreAuthorize: SERVICE_COUPON_SERVICE, SERVICE_ALL, MAIN_ADMIN, SUB_ADMIN, INSTRUCTOR" },
        { method: "GET", pathTemplate: "/coupons", description: "Get all coupons", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/coupons/{couponId}", description: "Get coupon details", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/coupons/validate/{code}", description: "Validate coupon by code", authRequired: true, authType: "Authentication" },
        { method: "PUT", pathTemplate: "/coupons/{couponId}", description: "Update coupon", authRequired: true, authType: "@PreAuthorize: SERVICE_COUPON_SERVICE, SERVICE_ALL, MAIN_ADMIN, SUB_ADMIN, INSTRUCTOR" },
        { method: "DELETE", pathTemplate: "/coupons/{couponId}", description: "Delete coupon", authRequired: true, authType: "@PreAuthorize: SERVICE_COUPON_SERVICE, SERVICE_ALL, MAIN_ADMIN, SUB_ADMIN, INSTRUCTOR" },
        { method: "PATCH", pathTemplate: "/coupons/{couponId}/activate", description: "Activate coupon", authRequired: true, authType: "@PreAuthorize: SERVICE_COUPON_SERVICE, SERVICE_ALL, MAIN_ADMIN, SUB_ADMIN, INSTRUCTOR" },
        { method: "PATCH", pathTemplate: "/coupons/{couponId}/deactivate", description: "Deactivate coupon", authRequired: true, authType: "@PreAuthorize: SERVICE_COUPON_SERVICE, SERVICE_ALL, MAIN_ADMIN, SUB_ADMIN, INSTRUCTOR" },
        { method: "GET", pathTemplate: "/coupons/my", description: "Get my coupons", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/coupons/campaigns", description: "Get campaigns", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/coupons/validate", description: "Validate coupon (full)", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/coupons/best-discount", description: "Get best discount", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/coupons/redeem", description: "Redeem coupon", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/coupons/assign-user", description: "Assign coupon to user", authRequired: true, authType: "@PreAuthorize: SERVICE_COUPON_SERVICE, SERVICE_ALL, MAIN_ADMIN, SUB_ADMIN, INSTRUCTOR" },
      ],
    },
  },
  "order_service": {
    "order_controller": {
      "postCreateOrder": buildRequester("order_service", "order_controller", "POST", "/orders/create", "Create order"),
      "getGetOrderById": buildRequester("order_service", "order_controller", "GET", "/orders/{orderId}", "Get order by ID"),
      "getGetAllOrders": buildRequester("order_service", "order_controller", "GET", "/orders", "Get all orders"),
      "getGetOrdersByUser": buildRequester("order_service", "order_controller", "GET", "/orders/user/{userId}", "Get orders by user"),
      "putUpdateOrderStatus": buildRequester("order_service", "order_controller", "PUT", "/orders/{orderId}/status", "Update order status"),
      "deleteCancelOrder": buildRequester("order_service", "order_controller", "DELETE", "/orders/{orderId}/cancel", "Cancel order"),
      "postRefundOrder": buildRequester("order_service", "order_controller", "POST", "/orders/{orderId}/refund", "Refund order"),
      $meta: [
        { method: "POST", pathTemplate: "/orders/create", description: "Create order", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/orders/{orderId}", description: "Get order by ID", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/orders", description: "Get all orders", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/orders/user/{userId}", description: "Get orders by user", authRequired: true, authType: "Authentication" },
        { method: "PUT", pathTemplate: "/orders/{orderId}/status", description: "Update order status", authRequired: true, authType: "Authentication" },
        { method: "DELETE", pathTemplate: "/orders/{orderId}/cancel", description: "Cancel order", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/orders/{orderId}/refund", description: "Refund order", authRequired: true, authType: "Authentication" },
      ],
    },
  },
  "payment_service": {
    "payment_controller": {
      "getGetAllPayments": buildRequester("payment_service", "payment_controller", "GET", "/payments", "Get all payments"),
      "postCreatePayment": buildRequester("payment_service", "payment_controller", "POST", "/payments/create", "Create payment"),
      "postCreateAndAutoPayHtml": buildRequester("payment_service", "payment_controller", "POST", "/payments/create-and-pay", "Create and auto-pay (HTML)"),
      "getCheckoutByTransactionIdHtml": buildRequester("payment_service", "payment_controller", "GET", "/payments/checkout/{txnId}", "Checkout by transaction ID (HTML)"),
      "getSuccessCallbackInfo": buildRequester("payment_service", "payment_controller", "GET", "/payments/callback/success", "Success callback info"),
      "getFailureCallbackInfo": buildRequester("payment_service", "payment_controller", "GET", "/payments/callback/failure", "Failure callback info"),
      "postHandleSuccessCallbackForm": buildRequester("payment_service", "payment_controller", "POST", "/payments/callback/success", "Handle success callback (form)"),
      "postHandleSuccessCallbackJson": buildRequester("payment_service", "payment_controller", "POST", "/payments/callback/success", "Handle success callback (JSON)"),
      "postHandleFailureCallbackForm": buildRequester("payment_service", "payment_controller", "POST", "/payments/callback/failure", "Handle failure callback (form)"),
      "postHandleFailureCallbackJson": buildRequester("payment_service", "payment_controller", "POST", "/payments/callback/failure", "Handle failure callback (JSON)"),
      "postVerifyPayment": buildRequester("payment_service", "payment_controller", "POST", "/payments/verify", "Verify payment"),
      "postPayuVerifyGateway": buildRequester("payment_service", "payment_controller", "POST", "/payments/payu/verify", "PayU verify gateway"),
      "postPayuCheckPayment": buildRequester("payment_service", "payment_controller", "POST", "/payments/payu/check-payment", "PayU check payment"),
      "postPayuGetTdr": buildRequester("payment_service", "payment_controller", "POST", "/payments/payu/tdr", "PayU get TDR"),
      "postPayuTransactionDetails": buildRequester("payment_service", "payment_controller", "POST", "/payments/payu/transaction-details", "PayU transaction details"),
      "postCreatePayuPaymentLink": buildRequester("payment_service", "payment_controller", "POST", "/payments/payu/payment-links", "Create PayU payment link"),
      "postPayuConsentCheckoutHtml": buildRequester("payment_service", "payment_controller", "POST", "/payments/payu/consent-checkout", "PayU consent checkout (HTML)"),
      "postInitiateRefund": buildRequester("payment_service", "payment_controller", "POST", "/payments/refund", "Initiate refund"),
      "getGetCoursePaymentsForInstructor": buildRequester("payment_service", "payment_controller", "GET", "/payments/instructor/{instructorId}/courses/{courseId}/payments", "Get course payments for instructor"),
      "getGetRefundStatus": buildRequester("payment_service", "payment_controller", "GET", "/payments/{txnId}/refund-status", "Get refund status"),
      "getGetInvoicePdf": buildRequester("payment_service", "payment_controller", "GET", "/payments/{txnId}/invoice", "Get invoice (PDF)"),
      "getGetInvoiceJson": buildRequester("payment_service", "payment_controller", "GET", "/payments/{txnId}/invoice-json", "Get invoice (JSON)"),
      $meta: [
        { method: "GET", pathTemplate: "/payments", description: "Get all payments", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/payments/create", description: "Create payment", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/payments/create-and-pay", description: "Create and auto-pay (HTML)", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/payments/checkout/{txnId}", description: "Checkout by transaction ID (HTML)", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/payments/callback/success", description: "Success callback info", authRequired: false, authType: "None" },
        { method: "GET", pathTemplate: "/payments/callback/failure", description: "Failure callback info", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/payments/callback/success", description: "Handle success callback (form)", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/payments/callback/success", description: "Handle success callback (JSON)", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/payments/callback/failure", description: "Handle failure callback (form)", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/payments/callback/failure", description: "Handle failure callback (JSON)", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/payments/verify", description: "Verify payment", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/payments/payu/verify", description: "PayU verify gateway", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/payments/payu/check-payment", description: "PayU check payment", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/payments/payu/tdr", description: "PayU get TDR", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/payments/payu/transaction-details", description: "PayU transaction details", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/payments/payu/payment-links", description: "Create PayU payment link", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/payments/payu/consent-checkout", description: "PayU consent checkout (HTML)", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/payments/refund", description: "Initiate refund", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/payments/instructor/{instructorId}/courses/{courseId}/payments", description: "Get course payments for instructor", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/payments/{txnId}/refund-status", description: "Get refund status", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/payments/{txnId}/invoice", description: "Get invoice (PDF)", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/payments/{txnId}/invoice-json", description: "Get invoice (JSON)", authRequired: true, authType: "Authentication" },
      ],
    },
    "test_course_controller": {
      "postCreateTestCourse": buildRequester("payment_service", "test_course_controller", "POST", "/test/courses", "Create test course"),
      "getListTestCourses": buildRequester("payment_service", "test_course_controller", "GET", "/test/courses", "List test courses"),
      "getGetTestCourse": buildRequester("payment_service", "test_course_controller", "GET", "/test/courses/{courseId}", "Get test course"),
      $meta: [
        { method: "POST", pathTemplate: "/test/courses", description: "Create test course", authRequired: false, authType: "None" },
        { method: "GET", pathTemplate: "/test/courses", description: "List test courses", authRequired: false, authType: "None" },
        { method: "GET", pathTemplate: "/test/courses/{courseId}", description: "Get test course", authRequired: false, authType: "None" },
      ],
    },
  },
  "review_service": {
    "review_controller": {
      "postCreateReview": buildRequester("review_service", "review_controller", "POST", "/reviews", "Create review"),
      "putUpdateOwnReview": buildRequester("review_service", "review_controller", "PUT", "/reviews/{reviewId}", "Update own review"),
      "deleteDeleteOwnReview": buildRequester("review_service", "review_controller", "DELETE", "/reviews/{reviewId}", "Delete own review"),
      "getGetReviewById": buildRequester("review_service", "review_controller", "GET", "/reviews/{reviewId}", "Get review by ID"),
      "getGetMyReviewForCourse": buildRequester("review_service", "review_controller", "GET", "/reviews/my/course/{courseId}", "Get my review for course"),
      "getGetPublicCourseReviews": buildRequester("review_service", "review_controller", "GET", "/reviews/course/{courseId}", "Get public course reviews"),
      "getGetCourseRatingSummary": buildRequester("review_service", "review_controller", "GET", "/reviews/course/{courseId}/summary", "Get course rating summary"),
      $meta: [
        { method: "POST", pathTemplate: "/reviews", description: "Create review", authRequired: true, authType: "Bearer Auth" },
        { method: "PUT", pathTemplate: "/reviews/{reviewId}", description: "Update own review", authRequired: true, authType: "Bearer Auth" },
        { method: "DELETE", pathTemplate: "/reviews/{reviewId}", description: "Delete own review", authRequired: true, authType: "Bearer Auth" },
        { method: "GET", pathTemplate: "/reviews/{reviewId}", description: "Get review by ID", authRequired: true, authType: "Bearer Auth" },
        { method: "GET", pathTemplate: "/reviews/my/course/{courseId}", description: "Get my review for course", authRequired: true, authType: "Bearer Auth" },
        { method: "GET", pathTemplate: "/reviews/course/{courseId}", description: "Get public course reviews", authRequired: false, authType: "None" },
        { method: "GET", pathTemplate: "/reviews/course/{courseId}/summary", description: "Get course rating summary", authRequired: false, authType: "None" },
      ],
    },
    "admin_review_controller": {
      "getListAllReviewsPaginated": buildRequester("review_service", "admin_review_controller", "GET", "/admin/reviews", "List all reviews (paginated)"),
      "getGetReviewDetails": buildRequester("review_service", "admin_review_controller", "GET", "/admin/reviews/{reviewUuid}", "Get review details"),
      "patchHideReview": buildRequester("review_service", "admin_review_controller", "PATCH", "/admin/reviews/{reviewUuid}/hide", "Hide review"),
      "patchUnhideReview": buildRequester("review_service", "admin_review_controller", "PATCH", "/admin/reviews/{reviewUuid}/unhide", "Unhide review"),
      "deleteDeleteAnyReview": buildRequester("review_service", "admin_review_controller", "DELETE", "/admin/reviews/{reviewUuid}", "Delete any review"),
      $meta: [
        { method: "GET", pathTemplate: "/admin/reviews", description: "List all reviews (paginated)", authRequired: true, authType: "Bearer Auth" },
        { method: "GET", pathTemplate: "/admin/reviews/{reviewUuid}", description: "Get review details", authRequired: true, authType: "Bearer Auth" },
        { method: "PATCH", pathTemplate: "/admin/reviews/{reviewUuid}/hide", description: "Hide review", authRequired: true, authType: "Bearer Auth" },
        { method: "PATCH", pathTemplate: "/admin/reviews/{reviewUuid}/unhide", description: "Unhide review", authRequired: true, authType: "Bearer Auth" },
        { method: "DELETE", pathTemplate: "/admin/reviews/{reviewUuid}", description: "Delete any review", authRequired: true, authType: "Bearer Auth" },
      ],
    },
  },
  "notification_service": {
    "notification_controller": {
      "postCreateNotification": buildRequester("notification_service", "notification_controller", "POST", "/notifications", "Create notification"),
      "postCreateBulkNotifications": buildRequester("notification_service", "notification_controller", "POST", "/notifications/bulk", "Create bulk notifications"),
      "getGetNotificationById": buildRequester("notification_service", "notification_controller", "GET", "/notifications/{id}", "Get notification by ID"),
      "getGetAllNotifications": buildRequester("notification_service", "notification_controller", "GET", "/notifications", "Get all notifications"),
      "getGetNotificationsByUser": buildRequester("notification_service", "notification_controller", "GET", "/notifications/user/{userId}", "Get notifications by user"),
      "getGetCombinedUserNotifications": buildRequester("notification_service", "notification_controller", "GET", "/notifications/user/{userId}/combined", "Get combined user notifications"),
      "putMarkAsRead": buildRequester("notification_service", "notification_controller", "PUT", "/notifications/{id}/read", "Mark as read"),
      "deleteDeleteNotification": buildRequester("notification_service", "notification_controller", "DELETE", "/notifications/{id}", "Delete notification"),
      "postRetryFailedNotification": buildRequester("notification_service", "notification_controller", "POST", "/notifications/{id}/retry", "Retry failed notification"),
      $meta: [
        { method: "POST", pathTemplate: "/notifications", description: "Create notification", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/notifications/bulk", description: "Create bulk notifications", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/notifications/{id}", description: "Get notification by ID", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/notifications", description: "Get all notifications", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/notifications/user/{userId}", description: "Get notifications by user", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/notifications/user/{userId}/combined", description: "Get combined user notifications", authRequired: true, authType: "Authentication" },
        { method: "PUT", pathTemplate: "/notifications/{id}/read", description: "Mark as read", authRequired: true, authType: "Authentication" },
        { method: "DELETE", pathTemplate: "/notifications/{id}", description: "Delete notification", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/notifications/{id}/retry", description: "Retry failed notification", authRequired: true, authType: "Authentication" },
      ],
    },
    "admin_notification_controller": {
      "postBroadcastNotification": buildRequester("notification_service", "admin_notification_controller", "POST", "/admin/broadcast", "Broadcast notification"),
      "postReprocessDlq": buildRequester("notification_service", "admin_notification_controller", "POST", "/admin/reprocess-dlq", "Reprocess DLQ"),
      "getGetSystemHealth": buildRequester("notification_service", "admin_notification_controller", "GET", "/admin/system-health", "Get system health"),
      "putUpdateNotificationSettings": buildRequester("notification_service", "admin_notification_controller", "PUT", "/admin/settings/notifications", "Update notification settings"),
      $meta: [
        { method: "POST", pathTemplate: "/admin/broadcast", description: "Broadcast notification", authRequired: true, authType: "Admin" },
        { method: "POST", pathTemplate: "/admin/reprocess-dlq", description: "Reprocess DLQ", authRequired: true, authType: "Admin" },
        { method: "GET", pathTemplate: "/admin/system-health", description: "Get system health", authRequired: true, authType: "Admin" },
        { method: "PUT", pathTemplate: "/admin/settings/notifications", description: "Update notification settings", authRequired: true, authType: "Admin" },
      ],
    },
    "user_notification_controller": {
      "getGetMyNotifications": buildRequester("notification_service", "user_notification_controller", "GET", "/users/me/notifications", "Get my notifications"),
      "getGetUnreadNotifications": buildRequester("notification_service", "user_notification_controller", "GET", "/users/me/unread", "Get unread notifications"),
      "putMarkAsRead": buildRequester("notification_service", "user_notification_controller", "PUT", "/users/me/read/{id}", "Mark as read"),
      "putMarkAllAsRead": buildRequester("notification_service", "user_notification_controller", "PUT", "/users/me/read-all", "Mark all as read"),
      "getGetUnreadCount": buildRequester("notification_service", "user_notification_controller", "GET", "/users/me/count", "Get unread count"),
      $meta: [
        { method: "GET", pathTemplate: "/users/me/notifications", description: "Get my notifications", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/users/me/unread", description: "Get unread notifications", authRequired: true, authType: "Authentication" },
        { method: "PUT", pathTemplate: "/users/me/read/{id}", description: "Mark as read", authRequired: true, authType: "Authentication" },
        { method: "PUT", pathTemplate: "/users/me/read-all", description: "Mark all as read", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/users/me/count", description: "Get unread count", authRequired: true, authType: "Authentication" },
      ],
    },
    "instructor_notification_controller": {
      "postNotifyInstructor": buildRequester("notification_service", "instructor_notification_controller", "POST", "/notifications/instructor/{instructorId}", "Notify instructor"),
      $meta: [
        { method: "POST", pathTemplate: "/notifications/instructor/{instructorId}", description: "Notify instructor", authRequired: false, authType: "None" },
      ],
    },
    "course_notification_controller": {
      "postNotifyCourseStudents": buildRequester("notification_service", "course_notification_controller", "POST", "/notifications/course/{courseId}", "Notify course students"),
      $meta: [
        { method: "POST", pathTemplate: "/notifications/course/{courseId}", description: "Notify course students", authRequired: false, authType: "None" },
      ],
    },
    "announcement_controller": {
      "postCreateAnnouncement": buildRequester("notification_service", "announcement_controller", "POST", "/announcements", "Create announcement"),
      "getGetDetailedAnnouncements": buildRequester("notification_service", "announcement_controller", "GET", "/announcements/course/{courseId}/detailed", "Get detailed announcements"),
      $meta: [
        { method: "POST", pathTemplate: "/announcements", description: "Create announcement", authRequired: false, authType: "None" },
        { method: "GET", pathTemplate: "/announcements/course/{courseId}/detailed", description: "Get detailed announcements", authRequired: false, authType: "None" },
      ],
    },
    "device_token_controller": {
      "postRegisterDeviceToken": buildRequester("notification_service", "device_token_controller", "POST", "/device-tokens", "Register device token"),
      $meta: [
        { method: "POST", pathTemplate: "/device-tokens", description: "Register device token", authRequired: true, authType: "X-User-Id header" },
      ],
    },
    "push_notification_controller": {
      "postSendPushToUsers": buildRequester("notification_service", "push_notification_controller", "POST", "/push/send", "Send push to users"),
      "postSendPushToTopic": buildRequester("notification_service", "push_notification_controller", "POST", "/push/topic", "Send push to topic"),
      "postBroadcastPush": buildRequester("notification_service", "push_notification_controller", "POST", "/push/broadcast", "Broadcast push"),
      $meta: [
        { method: "POST", pathTemplate: "/push/send", description: "Send push to users", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/push/topic", description: "Send push to topic", authRequired: false, authType: "None" },
        { method: "POST", pathTemplate: "/push/broadcast", description: "Broadcast push", authRequired: false, authType: "None" },
      ],
    },
    "system_controller": {
      "getGetSystemHealth": buildRequester("notification_service", "system_controller", "GET", "/system/health", "Get system health"),
      $meta: [
        { method: "GET", pathTemplate: "/system/health", description: "Get system health", authRequired: false, authType: "None" },
      ],
    },
    "template_controller": {
      "postCreateTemplate": buildRequester("notification_service", "template_controller", "POST", "/templates", "Create template"),
      "getGetTemplatesPaginated": buildRequester("notification_service", "template_controller", "GET", "/templates", "Get templates (paginated)"),
      "putUpdateTemplate": buildRequester("notification_service", "template_controller", "PUT", "/templates/{id}", "Update template"),
      "deleteDeleteTemplate": buildRequester("notification_service", "template_controller", "DELETE", "/templates/{id}", "Delete template"),
      $meta: [
        { method: "POST", pathTemplate: "/templates", description: "Create template", authRequired: false, authType: "None" },
        { method: "GET", pathTemplate: "/templates", description: "Get templates (paginated)", authRequired: false, authType: "None" },
        { method: "PUT", pathTemplate: "/templates/{id}", description: "Update template", authRequired: false, authType: "None" },
        { method: "DELETE", pathTemplate: "/templates/{id}", description: "Delete template", authRequired: false, authType: "None" },
      ],
    },
    "preference_controller": {
      "getGetPreferences": buildRequester("notification_service", "preference_controller", "GET", "/preferences", "Get preferences"),
      "putUpdatePreferences": buildRequester("notification_service", "preference_controller", "PUT", "/preferences", "Update preferences"),
      $meta: [
        { method: "GET", pathTemplate: "/preferences", description: "Get preferences", authRequired: false, authType: "None" },
        { method: "PUT", pathTemplate: "/preferences", description: "Update preferences", authRequired: false, authType: "None" },
      ],
    },
    "assignment_reminder_controller": {
      "postSendAssignmentReminder": buildRequester("notification_service", "assignment_reminder_controller", "POST", "/assignments/reminder", "Send assignment reminder"),
      $meta: [
        { method: "POST", pathTemplate: "/assignments/reminder", description: "Send assignment reminder", authRequired: false, authType: "None" },
      ],
    },
    "certificate_notify_controller": {
      "postNotifyCertificateUsers": buildRequester("notification_service", "certificate_notify_controller", "POST", "/certificates/notify", "Notify certificate users"),
      $meta: [
        { method: "POST", pathTemplate: "/certificates/notify", description: "Notify certificate users", authRequired: false, authType: "None" },
      ],
    },
    "live_class_reminder_controller": {
      "postSendLiveClassReminder": buildRequester("notification_service", "live_class_reminder_controller", "POST", "/live-class/reminder", "Send live class reminder"),
      $meta: [
        { method: "POST", pathTemplate: "/live-class/reminder", description: "Send live class reminder", authRequired: false, authType: "None" },
      ],
    },
  },
  "wishlist_service": {
    "wishlist_controller": {
      "postAddCourseToWishlist": buildRequester("wishlist_service", "wishlist_controller", "POST", "/wishlist", "Add course to wishlist"),
      "getGetUserWishlist": buildRequester("wishlist_service", "wishlist_controller", "GET", "/wishlist", "Get user wishlist"),
      "getGetWishlistItemById": buildRequester("wishlist_service", "wishlist_controller", "GET", "/wishlist/{wishlistId}", "Get wishlist item by ID"),
      "getCheckIfCourseInWishlist": buildRequester("wishlist_service", "wishlist_controller", "GET", "/wishlist/check/{courseId}", "Check if course in wishlist"),
      "postMoveCourseToCart": buildRequester("wishlist_service", "wishlist_controller", "POST", "/wishlist/{courseId}/move-to-cart", "Move course to cart"),
      "deleteRemoveFromWishlist": buildRequester("wishlist_service", "wishlist_controller", "DELETE", "/wishlist/{courseId}", "Remove from wishlist"),
      "deleteClearWishlist": buildRequester("wishlist_service", "wishlist_controller", "DELETE", "/wishlist", "Clear wishlist"),
      $meta: [
        { method: "POST", pathTemplate: "/wishlist", description: "Add course to wishlist", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/wishlist", description: "Get user wishlist", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/wishlist/{wishlistId}", description: "Get wishlist item by ID", authRequired: true, authType: "Authentication" },
        { method: "GET", pathTemplate: "/wishlist/check/{courseId}", description: "Check if course in wishlist", authRequired: true, authType: "Authentication" },
        { method: "POST", pathTemplate: "/wishlist/{courseId}/move-to-cart", description: "Move course to cart", authRequired: true, authType: "Authentication" },
        { method: "DELETE", pathTemplate: "/wishlist/{courseId}", description: "Remove from wishlist", authRequired: true, authType: "Authentication" },
        { method: "DELETE", pathTemplate: "/wishlist", description: "Clear wishlist", authRequired: true, authType: "Authentication" },
      ],
    },
  },
};

export default generatedApiClient;
